### ISSUE TITLE
All modules with native libraries must support the same set of ABIs.

### ISSUE THREAD

**Issue by marlonl3001** [blinkcard/blinkcard-android#19]
### Description

I´m trying to implement the sdk inside an on-demand dynamic feature.
Maven and implementation statements are written in the module's build.gradle, like the image below:

<img width="622" alt="build gradle" src="https://user-images.githubusercontent.com/6325593/140333333-2aeba793-4222-43ff-97c7-888691adb0a8.png">

When I try to compile the app, I got the following error:

<img width="896" alt="manifest_error" src="https://user-images.githubusercontent.com/6325593/140551099-24f38d21-5d77-4c0d-bf11-ef4aab0bffe4.png">

```
All modules with native libraries must support the same set of ABIs, but module 'base' supports '[ARM64_V8A, ARMEABI_V7A, ARMEABI, X86, X86_64]' and module 'cardscan' supports '[ARM64_V8A, ARMEABI_V7A, X86, X86_64]'.
```

When I move maven declaration to top level build.gradle and library implementation to build.gradle (app), it works fine, but I need to implement it in an on-demand module.

### Environment Details

**BlinkCard version:**
2.4.0

**Comment by anjapenic** [comment]
Hello @marlonl3001,

Thanks for waiting for our answer. Since our SDKs are using the latest Android NDK which doesn’t support armeabi CPUs, you should add an abiFilter to the build.gradle of your base module which would filter out the armeabi architecture.
This way the modules would have matching sets of supported ABI’s and your code should compile.
You can do this by adding this section to your base modules build.gradle:

```
android {
    defaultConfig {
        ndk {
            abiFilters 'ARM64_V8A', 'ARMEABI_V7A', 'X86', 'X86_64'
        }
    }
} 
```

Best regards,
Anja
